#!/bin/sh

usage (){
    echo "Usage: netnstools enter [NAMESPACE]"
    echo "       netnstools run [NAMESPACE] [COMMAND]"
}

if [[ "$1" == "enter" ]]; then
    sudo ip netns exec $2 sudo -u  $USER bash 
elif [[ "$1" == "run" ]]; then
    sudo ip netns exec $2 sudo -u  $USER $3 
else
    usage
fi
