---
#- name: Install the nextcloud flatpak
#  community.general.flatpak:
#    name: com.nextcloud.desktopclient.nextcloud 
#    method: user
#    state: present

- name: Install nextcloud user systemd
  copy:
    src: nextcloud_client.service
    dest: ~/.config/systemd/user/nextcloud_client.service
  notify:
    - Start nextcloud_client
